# =============================================================================
# IMPORTANT: Secrets are read from environment variables!
# =============================================================================
# These are automatically set by GitHub Actions from repository secrets.
# Variables are passed via TF_VAR_* environment variables.
# =============================================================================

# =============================================================================
# Hetzner Cloud
# =============================================================================

variable "hcloud_token" {
  description = "Hetzner Cloud API token (set via TF_VAR_hcloud_token)"
  type        = string
  sensitive   = true
  # No default - must be provided via environment variable
}

variable "server_type" {
  description = "Hetzner server type (e.g., cax11, cax21, cpx21)"
  type        = string
  default     = "cax31"  # 4 vCPU, 8GB RAM (ARM)
}

variable "server_location" {
  description = "Hetzner datacenter location"
  type        = string
  default     = "fsn1"  # Falkenstein, Germany
}

variable "server_image" {
  description = "OS image for the server"
  type        = string
  default     = "ubuntu-24.04"
}

variable "ipv6_only" {
  description = "Use IPv6 only (no public IPv4). Reduces costs by ~€4/month."
  type        = bool
  # NOTE: IPv6-only is currently disabled due to connectivity issues.
  # IPv6-only servers cannot download cloudflared from GitHub or pkg.cloudflare.com
  # (TLS handshake failures over IPv6). See issue #130 for progress on IPv6 support.
  default     = false
}

variable "ssh_public_key_path" {
  description = "Path to SSH public key file (generated by GitHub Actions)"
  type        = string
  # No default - provided by setup-control-plane workflow
}

variable "ssh_private_key_path" {
  description = "Path to SSH private key file (generated by GitHub Actions)"
  type        = string
  # No default - provided by setup-control-plane workflow
}

# =============================================================================
# Cloudflare
# =============================================================================

variable "cloudflare_api_token" {
  description = "Cloudflare API token (set via TF_VAR_cloudflare_api_token)"
  type        = string
  sensitive   = true
  # No default - must be provided via environment variable
}

variable "cloudflare_account_id" {
  description = "Cloudflare Account ID (set via TF_VAR_cloudflare_account_id)"
  type        = string
  # No default - must be provided via environment variable
}

variable "cloudflare_zone_id" {
  description = "Cloudflare Zone ID for your domain"
  type        = string
}

variable "domain" {
  description = "Your domain name (e.g., example.com)"
  type        = string
}

variable "admin_email" {
  description = "Admin email for Cloudflare Access (full access including SSH)"
  type        = string
}

variable "user_email" {
  description = "Regular user email for Cloudflare Access (all services except SSH). Optional."
  type        = string
  default     = ""
}

variable "admin_username" {
  description = "Admin username for services like Portainer, Uptime Kuma (default: nexus)"
  type        = string
  default     = "nexus"
}

# =============================================================================
# Services
# =============================================================================

variable "services" {
  description = "Map of services to expose via Cloudflare Tunnel"
  type = map(object({
    enabled        = bool
    subdomain      = string
    port           = number
    public         = bool   # true = no auth, false = behind Cloudflare Access
    description    = optional(string, "")
    core           = optional(bool, false)
    image          = optional(string, "")
    support_images = optional(map(string), {})
  }))
  default = {}
}

# =============================================================================
# Firewall Rules (external TCP access)
# =============================================================================

variable "firewall_rules" {
  description = "Firewall rules for external TCP access (e.g., Kafka, PostgreSQL, MinIO S3)"
  type = map(object({
    port       = number
    protocol   = string
    source_ips = list(string)
    dns_record = optional(string, "")
  }))
  default = {}
}

# =============================================================================
# Docker Hub (optional - for increased pull rate limits)
# =============================================================================

variable "dockerhub_username" {
  description = "Docker Hub username (optional, set via TF_VAR_dockerhub_username)"
  type        = string
  default     = ""
}

variable "dockerhub_token" {
  description = "Docker Hub access token (optional, set via TF_VAR_dockerhub_token)"
  type        = string
  sensitive   = true
  default     = ""
}

# =============================================================================
# GitHub (shared with control-plane, declared here to avoid warnings)
# =============================================================================

# =============================================================================
# Hetzner Object Storage (for LakeFS)
# =============================================================================
# Bucket is created in control-plane to survive teardown.
# Server/region are configured in control-plane with sensible defaults.
# Access key and secret key are secrets (stored in GitHub Secrets).

variable "hetzner_object_storage_access_key" {
  description = "Hetzner Object Storage S3 access key (created in Hetzner Console)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "hetzner_object_storage_secret_key" {
  description = "Hetzner Object Storage S3 secret key (created in Hetzner Console)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "hetzner_object_storage_server" {
  description = "Hetzner Object Storage server (from control-plane output)"
  type        = string
  default     = "fsn1.your-objectstorage.com"
}

variable "hetzner_object_storage_region" {
  description = "Hetzner Object Storage region (from control-plane output)"
  type        = string
  default     = "fsn1"
}

variable "hetzner_s3_bucket" {
  description = "Hetzner Object Storage bucket name (from control-plane output)"
  type        = string
  default     = ""
}

variable "hetzner_s3_bucket_general" {
  description = "Hetzner Object Storage bucket (general purpose, from control-plane output)"
  type        = string
  default     = ""
}

variable "persistent_volume_id" {
  description = "Hetzner Cloud Volume ID for persistent storage (from control-plane output, 0 = no volume)"
  type        = number
  default     = 0
}

variable "github_owner" {
  description = "GitHub repository owner (used by control-plane module)"
  type        = string
  default     = ""
}

variable "github_repo" {
  description = "GitHub repository name (used by control-plane module)"
  type        = string
  default     = ""
}
